Adds verification steps to the deploy workflow
Adds verification steps to the deployment workflow to ensure that the Yandex CLI is properly configured and that the kubeconfig file is correctly generated.
This will help to catch configuration issues earlier in the deployment process.

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -43,6 +43,10 @@ jobs:
         yc config set service-account-key sa-key.json
         yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
         yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
+    - name: Verify Yandex CLI
+      run: |
+        yc version
+        yc iam service-account get --name ci-cd-sa || echo "Failed to get SA"
     - name: Set up kubectl
       uses: azure/setup-kubectl@v4
       with:
@@ -50,7 +54,11 @@ jobs:
     - name: Generate kubeconfig
       run: |
         yc managed-kubernetes cluster get-credentials --id ${{ secrets.YC_CLUSTER_ID }} --external --kubeconfig kubeconfig.yaml
+        cat kubeconfig.yaml || echo "Failed to create kubeconfig"
         export KUBECONFIG=$PWD/kubeconfig.yaml
+    - name: Verify kubeconfig
+      run: |
+        kubectl cluster-info
     - name: Update Deployments
       run: |
         kubectl -n aeromap set image deployment/aeromap-backend aeromap-backend=cr.yandex/${{ secrets.YC_REG_ID }}/aeromap-backend:${{ github.sha }}
